[tool.poetry]
name = "gpustack"
version = "0.0.1"
description = "GPU Stack"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
include = ["*/third_party/**/*","*/ui/**/*"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
sqlmodel = "^0.0.18"
pydantic-settings = "^2.2.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
setproctitle = "^1.3.3"
inflection = "^0.5.1"
openai = "^1.31.1"
netifaces = "^0.11.0"


prometheus-client = "^0.20.0"
colorama = "^0.4.6"
psutil = "^5.9.8"
requests = "^2.32.3"
huggingface-hub = "^0.23.3"
attrs = "^23.2.0"
[tool.poetry.group.dev.dependencies]
coverage = {extras = ["toml"], version = "^7.5.1"}
flake8 = "^7.0.0"
flake8-bugbear = "^24.4.26"
black = "^24.4.2"
pytest = "^8.2.0"
openapi-python-client = "^0.20.0"

deptry = "^0.16.1"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gpustack = "gpustack.main:main"
gen = "gpustack.codegen.generate:main"

[tool.black]
exclude = '''
/(
    generated_client
)/
'''
