[tool.poetry]
name = "gpustack"
version = "0.0.1"
description = "GPU Stack"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
sqlmodel = "^0.0.18"
transformers = "^4.40.2"
pydantic-settings = "^2.2.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
torch = "^2.3.0"
accelerate = "^0.30.0"
bcrypt = "4.0.1"
python-dateutil = "^2.9.0.post0"
setproctitle = "^1.3.3"
inflection = "^0.5.1"
llama-cpp-python = {extras = ["server"], version = "^0.2.77"}
openai = "^1.31.1"
netifaces = "^0.11.0"


prometheus-client = "^0.20.0"
hf-transfer = "^0.1.6"
[tool.poetry.group.dev.dependencies]
coverage = {extras = ["toml"], version = "^7.5.1"}
flake8 = "^7.0.0"
flake8-bugbear = "^24.4.26"
black = "^24.4.2"
pytest = "^8.2.0"
openapi-python-client = "^0.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gpustack = "gpustack.main:main"
gen = "gpustack.codegen.generate:main"

[tool.black]
exclude = '''
/(
    generated_client
)/
'''
