name: CI

on:
  push:
    branches: [main]
    tags: ["*.*.*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry/artifacts
            ~/.cache/pypoetry/repository
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          make install

      - name: Lint with Flake8
        run: |
          make lint

      - name: Run Tests
        run: |
          make test

      - name: Build
        run: |
          make build

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PYPI_API_TOKEN: ${{ secrets.CI_PYPI_API_TOKEN }}
        run: |
          make publish-pypi
